import 'package:bearlysocial/enums/interest.dart';

Map<String, Interest> get interests => {
      'Basketball': Interest.basketball,
      'Swimming': Interest.swimming,
      'Genetic Engineering': Interest.geneticEngineering,
      'Playing Musical Instruments': Interest.playingMusicalInstruments,
      'Photography': Interest.photography,
      'Cycling': Interest.cycling,
      'Climate Change': Interest.climateChange,
      'Hiking': Interest.hiking,
      'Politics': Interest.politics,
      'Immigration': Interest.immigration,
      'Rugby': Interest.rugby,
      'Watching Movies': Interest.watchingMovies,
      'Yoga': Interest.yoga,
      'Gardening': Interest.gardening,
      'Warfare': Interest.warfare,
      'Badminton': Interest.badminton,
      'Coding': Interest.coding,
      'Traveling': Interest.traveling,
      'Martial Arts': Interest.martialArts,
      'Fishing': Interest.fishing,
      'Sewing': Interest.sewing,
      'Volunteering': Interest.volunteering,
      'Ice Hockey': Interest.iceHockey,
      'Meditation': Interest.meditation,
      'Birdwatching': Interest.birdwatching,
      'Writing': Interest.writing,
      'Cybersecurity': Interest.cybersecurity,
      'Dancing': Interest.dancing,
      'Rocket Science': Interest.rocketScience,
      'Collecting': Interest.collecting,
      'History': Interest.history,
      'Mental Health': Interest.mentalHealth,
      'Cooking': Interest.cooking,
      'Astronomy': Interest.astronomy,
      'Racial Inequality': Interest.racialInequality,
      'Chess': Interest.chess,
      'Golf': Interest.golf,
      'Football': Interest.footBall,
      'Novels': Interest.novels,
      'Camping': Interest.camping,
      'Tennis': Interest.tennis,
      'Gaming': Interest.gaming,
      'Comic Books': Interest.comicBooks,
      'Mathematics': Interest.mathematics,
      'Baseball': Interest.baseball,
      'DIY Projects': Interest.diyProjects,
      'Economy': Interest.economy,
      'Drawing': Interest.drawing,
      'Painting': Interest.painting,
      'Parkour': Interest.parkour,
      'LGBT Rights': Interest.lgbtRights,
      'Volleyball': Interest.volleyball,
      'Stock Market': Interest.stockMarket,
      'Artificial Intelligence': Interest.artificialIntelligence,
      'Quantum Physics': Interest.quantumPhysics,
      'Running': Interest.running,
    };
